#!/bin/bash
#http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

#12d1:1506 adalah pid:vid untuk mode modem
while true; do
	echo "Checking modem at `date` ..."
	lsusb | grep "12d1:1465" > /dev/null
	if [ $? -eq 1 ]; then
		echo "Switching to modem mode..."
		sudo usb_modeswitch -c $DIR/usb_modeswitch.conf > /dev/null 2>&1
		sleep 5
		lsusb | grep "12d1:1465" > /dev/null
		if [ $? -eq 0 ]; then
			echo "Modem activated..."
		else
			echo "Modem activation failed..."
		fi
	else
		echo "Modem already activated...."
	fi
	
	sleep 30
done
